### ISSUE TITLE
Nullpointer when trying to convert the locked inventory to itemstack  - silverforte@Spigot

### ISSUE THREAD

**Issue by Nutty101** [Nutty101/NPC-Police#4]
[16:49:15] [Thread-16/WARN]: java.lang.NullPointerException
[16:49:15] [Thread-16/WARN]: at net.livecar.nuttyworks.npc_police.utilities.Utilities.serialzeItemStack(Utilities.java:263)
[16:49:15] [Thread-16/WARN]: at net.livecar.nuttyworks.npc_police.players.Arrest_Record.serializeLockedInventory(Arrest_Record.java:637)
[16:49:15] [Thread-16/WARN]: at net.livecar.nuttyworks.npc_police.database.Database_SqlLite.saveUserData(Database_SqlLite.java:342)
[16:49:15] [Thread-16/WARN]: at net.livecar.nuttyworks.npc_police.database.Database_SqlLite.processQueue(Database_SqlLite.java:177)
[16:49:15] [Thread-16/WARN]: at net.livecar.nuttyworks.npc_police.database.Database_SqlLite.run(Database_SqlLite.java:124)
[16:49:15] [Thread-16/WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by Nutty101** [comment]
Forgot to check if the DB field was null.  OOPS.  Fixed in 2.0.9

**Comment by Nutty101** [comment]
This has been resolved. Closing it out.
