### ISSUE TITLE
Dev builds with a bad version string are breaking the startup sequence

### ISSUE THREAD

**Issue by Nutty101** [Nutty101/NPC-Police#55]
06.07 17:02:47 [Server] INFO java.lang.IllegalArgumentException: named capturing group is missing trailing '}'
06.07 17:02:47 [Server] INFO at java.util.regex.Matcher.appendReplacement(Matcher.java:841) ~[?:1.8.0_242]
06.07 17:02:47 [Server] INFO at java.util.regex.Matcher.replaceAll(Matcher.java:955) ~[?:1.8.0_242]
06.07 17:02:47 [Server] INFO at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_242]

Need to add a check for things like this.
Placeholder API = 2.10.7-DEV-${BUILD-NUMBER}

**Comment by Nutty101** [comment]
This has been resolved.
